server:
  port: 8080

spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    url: jdbc:mysql://localhost:3306/event_db?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: admin
    password: adminsql1@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQL8Dialect
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        id:
          new_generator_mappings: true
        format_sql: true
        use_sql_comments: true
        show_sql: false
        hbm2ddl:
          auto: update

logging:
  level:
    org:
      hibernate: info